import { DatabaseSync } from 'node:sqlite';
import { createHash, pbkdf2Sync, randomBytes, timingSafeEqual } from 'node:crypto';
import { mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
const empty=()=>({revision:0,theme:'cyberpunk',language:'de',projects:[],boards:[],columns:[],tasks:[],focusNotes:[],activeProjectId:null});
const hash=(p,s)=>pbkdf2Sync(p,s,600000,32,'sha256'); const tokenHash=t=>createHash('sha256').update(t||'').digest('hex');
export class Profiles {
 constructor(path){mkdirSync(dirname(path),{recursive:true});this.db=new DatabaseSync(path);this.db.exec(awaitedSchema);try{this.db.exec('ALTER TABLE users ADD COLUMN email TEXT')}catch{}for(const name of ['Sascha','Jessica']){const id=name.toLowerCase();if(!this.db.prepare('SELECT id FROM users WHERE id=?').get(id)){const salt=randomBytes(16);this.db.prepare('INSERT INTO users(id,name,salt,password_hash) VALUES(?,?,?,?)').run(id,name,salt,hash('1234',salt));}this.db.prepare('INSERT OR IGNORE INTO personal_workspaces VALUES(?,?)').run(id,JSON.stringify(empty()));}this.db.prepare('INSERT OR IGNORE INTO shared_workspace(id,data) VALUES(1,?)').run(JSON.stringify(empty())); }
 close(){this.db.close()} global(){return JSON.parse(this.db.prepare('SELECT data FROM shared_workspace WHERE id=1').get().data)} members(){return this.db.prepare('SELECT * FROM board_members').all()}
 public(id){return this.db.prepare('SELECT id,name,avatar,email FROM users WHERE id=?').get(id)}
 login(name,password){const u=this.db.prepare('SELECT * FROM users WHERE lower(name)=lower(?)').get(name),now=Date.now();if(!u||u.locked_until>now||typeof password!=='string'||!timingSafeEqual(hash(password,u.salt),u.password_hash)){if(u)this.db.prepare('UPDATE users SET failures=failures+1,locked_until=? WHERE id=?').run(u.failures>=4?now+60000:0,u.id);throw Error('Benutzername oder Passwort falsch.');}this.db.prepare('UPDATE users SET failures=0,locked_until=0 WHERE id=?').run(u.id);const token=randomBytes(32).toString('hex');this.db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(tokenHash(token),u.id,now+604800000);return {token,user:this.public(u.id)}}
 user(token){const s=this.db.prepare('SELECT user_id FROM sessions WHERE token_hash=? AND expires>?').get(tokenHash(token),Date.now());if(!s)throw Object.assign(Error('Bitte anmelden.'),{status:401});return s.user_id}
 logout(token){this.db.prepare('DELETE FROM sessions WHERE token_hash=?').run(tokenHash(token));}
 load(id){const personal=JSON.parse(this.db.prepare('SELECT data FROM personal_workspaces WHERE user_id=?').get(id).data),g=this.global(),ids=new Set(this.members().filter(m=>m.user_id===id).map(m=>m.board_id)),boards=g.boards.filter(b=>ids.has(b.id)),projects=g.projects.filter(project=>boards.some(b=>b.projectId===project.id)),columns=g.columns.filter(c=>ids.has(c.boardId)),tasks=g.tasks.filter(t=>columns.some(c=>c.id===t.columnId));return {...personal,ownerId:id,revision:g.revision,boards,projects,columns,tasks,focusNotes:(g.focusNotes||[]).filter(n=>tasks.some(t=>t.id===n.taskId)||(!n.taskId&&n.ownerId===id)),activeProjectId:projects.some(project=>project.id===personal.activeProjectId)?personal.activeProjectId:projects[0]?.id||null}}
 save(id,state){const g=this.global();if(g.revision!==state.revision)throw Error('Die Daten wurden in einem anderen Fenster geändert. Bitte neu laden.');const prior=this.load(id),members=this.members(),allowed=new Set(prior.boards.map(b=>b.id)),oldBoardIds=new Set(g.boards.map(b=>b.id));for(const b of state.boards){if(!oldBoardIds.has(b.id))this.db.prepare("INSERT OR IGNORE INTO board_members VALUES(?,?,'owner')").run(b.id,id)}for(const key of ['projects','boards','columns','tasks','focusNotes']){const old=(g[key]||[]),visible=key==='boards'?allowed:new Set((prior[key]||[]).map(x=>x.id));if((state[key]||[]).some(x=>old.some(y=>y.id===x.id)&&!visible.has(x.id)))throw Error('Kein Zugriff auf dieses Board.');g[key]=[...old.filter(x=>!visible.has(x.id)),...(state[key]||[]).map(x=>key==='focusNotes'?{...x,ownerId:old.find(y=>y.id===x.id)?.ownerId||id}:x)]}g.revision++;this.db.prepare('UPDATE shared_workspace SET revision=?,data=? WHERE id=1').run(g.revision,JSON.stringify(g));const personal={...state,ownerId:id};for(const k of ['projects','boards','columns','tasks','focusNotes'])delete personal[k];this.db.prepare('UPDATE personal_workspaces SET data=? WHERE user_id=?').run(JSON.stringify(personal),id);return g.revision}
 membersFor(id,boardId){if(!this.members().some(m=>m.board_id===boardId&&m.user_id===id))throw Error('Kein Zugriff.');const users=this.db.prepare('SELECT id,name,avatar FROM users ORDER BY name COLLATE NOCASE').all();const boardMembers=this.members();const myBoards=new Set(boardMembers.filter(m=>m.user_id===id&&m.board_id!==boardId).map(m=>m.board_id));const suggestedIds=new Set(boardMembers.filter(m=>myBoards.has(m.board_id)).map(m=>m.user_id));return {members:this.db.prepare('SELECT u.id,u.name,u.avatar,m.role FROM board_members m JOIN users u ON u.id=m.user_id WHERE m.board_id=? ORDER BY m.role,u.name').all(boardId),users,suggested:users.filter(u=>u.id!==id&&suggestedIds.has(u.id))}}
 createUser(name,password){const clean=String(name??'').trim();if(clean.length<2||clean.length>80||!String(password??'').match(/^.{4,256}$/))throw Error('Name und Passwort prüfen.');const id=`user-${clean.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')}-${randomBytes(3).toString('hex')}`;const salt=randomBytes(16);try{this.db.prepare('INSERT INTO users(id,name,salt,password_hash) VALUES(?,?,?,?)').run(id,clean,salt,hash(password,salt));this.db.prepare('INSERT INTO personal_workspaces VALUES(?,?)').run(id,JSON.stringify(empty()));return this.public(id)}catch{throw Error('Dieser Benutzername ist bereits vergeben.')}}
 invite(id,boardId,userId){if(!this.members().some(m=>m.board_id===boardId&&m.user_id===id&&m.role==='owner'))throw Error('Nur der Eigentümer kann Mitglieder hinzufügen.');this.db.prepare("INSERT OR IGNORE INTO board_members VALUES(?,?,'editor')").run(boardId,userId);return this.membersFor(id,boardId)}
 profile(id,b){const name=String(b.name??'').trim(),email=String(b.email??'').trim();if(name&&(name.length<2||name.length>80))throw Error('Der Name benötigt 2–80 Zeichen.');if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw Error('Bitte eine gültige E-Mail-Adresse eingeben.');if(name||b.email!==undefined)this.db.prepare('UPDATE users SET name=?,email=? WHERE id=?').run(name||this.public(id).name,email||null,id);if(b.avatar!==undefined)this.db.prepare('UPDATE users SET avatar=? WHERE id=?').run(b.avatar,id);if(b.newPassword){if(!b.currentPassword||b.newPassword.length<4)throw Error('Passwort benötigt mindestens 4 Zeichen.');const u=this.db.prepare('SELECT * FROM users WHERE id=?').get(id);if(!timingSafeEqual(hash(b.currentPassword,u.salt),u.password_hash))throw Error('Aktuelles Passwort falsch.');const salt=randomBytes(16);this.db.prepare('UPDATE users SET salt=?,password_hash=? WHERE id=?').run(salt,hash(b.newPassword,salt),id);this.db.prepare('DELETE FROM sessions WHERE user_id=?').run(id)}return this.public(id)} }
const awaitedSchema=`PRAGMA foreign_keys=ON; CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY,name TEXT NOT NULL UNIQUE,salt BLOB NOT NULL,password_hash BLOB NOT NULL,avatar TEXT,email TEXT,failures INTEGER NOT NULL DEFAULT 0,locked_until INTEGER NOT NULL DEFAULT 0); CREATE TABLE IF NOT EXISTS sessions (token_hash TEXT PRIMARY KEY,user_id TEXT NOT NULL,expires INTEGER NOT NULL); CREATE TABLE IF NOT EXISTS personal_workspaces (user_id TEXT PRIMARY KEY,data TEXT NOT NULL); CREATE TABLE IF NOT EXISTS shared_workspace (id INTEGER PRIMARY KEY CHECK(id=1),revision INTEGER NOT NULL DEFAULT 0,data TEXT NOT NULL); CREATE TABLE IF NOT EXISTS board_members (board_id TEXT,user_id TEXT,role TEXT NOT NULL,PRIMARY KEY(board_id,user_id));`;
